import sys
import struct
from PIL import Image, ImageFilter
import numpy as np
import io

def generate_triangles_vectorized(data, scale):
    """Vectorised triangle generator, returns arrays for X0,Y0,X1,Y1 and h1..h4"""
    h, w = data.shape
    h1 = data[:-1, :-1] * scale
    h2 = data[:-1, 1:]  * scale
    h3 = data[1:, :-1]  * scale
    h4 = data[1:, 1:]   * scale

    y = np.arange(h - 1, dtype=np.float32) * scale
    x = np.arange(w - 1, dtype=np.float32) * scale
    X0, Y0 = np.meshgrid(x, y)
    X1 = X0 + scale
    Y1 = Y0 + scale

    return X0, Y0, X1, Y1, h1, h2, h3, h4

def stream_stl(triangle_arrays, out_stream):
    """Stream triangles directly to a binary STL in chunks"""
    X0, Y0, X1, Y1, h1, h2, h3, h4 = triangle_arrays
    h_blocks, w_blocks = h1.shape

    # 80-byte header
    header = b"Generated by image_to_stl"
    out_stream.write(header.ljust(80, b" "))

    # Triangle count
    n_triangles = h_blocks * w_blocks * 2
    out_stream.write(struct.pack("<I", n_triangles))

    # Stream triangles row by row (memory-efficient)
    for y in range(h_blocks):
        for x in range(w_blocks):
            # Vertex coordinates
            v1 = (X0[y, x], Y0[y, x], h1[y, x])
            v2 = (X1[y, x], Y0[y, x], h2[y, x])
            v3 = (X0[y, x], Y1[y, x], h3[y, x])
            v4 = (X1[y, x], Y1[y, x], h4[y, x])

            # Triangle 1
            out_stream.write(struct.pack("<3f", 0.0, 0.0, 0.0))  # normal
            out_stream.write(struct.pack("<3f", *v1))
            out_stream.write(struct.pack("<3f", *v2))
            out_stream.write(struct.pack("<3f", *v3))
            out_stream.write(struct.pack("<H", 0))  # attribute byte count

            # Triangle 2
            out_stream.write(struct.pack("<3f", 0.0, 0.0, 0.0))  # normal
            out_stream.write(struct.pack("<3f", *v2))
            out_stream.write(struct.pack("<3f", *v4))
            out_stream.write(struct.pack("<3f", *v3))
            out_stream.write(struct.pack("<H", 0))

def main():
    if len(sys.argv) < 3:
        print("Usage: python image_to_stl.py <max_height> <blur_radius>", file=sys.stderr)
        return

    max_height = float(sys.argv[1])
    blur_radius = int(sys.argv[2])

    # Read image bytes from stdin
    image_bytes = sys.stdin.buffer.read()
    if not image_bytes:
        print("ERROR: No image data received on stdin.", file=sys.stderr)
        sys.exit(1)

    img = Image.open(io.BytesIO(image_bytes))

    # Handle transparency
    if img.mode in ("RGBA", "LA"):
        bg = Image.new("RGB", img.size, (255, 255, 255))
        bg.paste(img, mask=img.split()[-1])
        img = bg

    # Grayscale + blur
    img = img.convert("L").filter(ImageFilter.GaussianBlur(blur_radius))

    # Build heightmap
    data = (1.0 - (np.array(img) / 255.0)) * max_height
    data = np.flipud(data)

    scale = 0.01

    # Generate triangle arrays (vectorised, no huge triangle array in memory)
    triangle_arrays = generate_triangles_vectorized(data, scale)

    # Stream STL to stdout
    stream_stl(triangle_arrays, sys.stdout.buffer)

if __name__ == "__main__":
    main()