import sys
import io
import struct
from PIL import Image, ImageFilter
import numpy as np
from stl import mesh


def mesh_to_stl_bytes(stl_mesh):
    """
    Convert a numpy-stl mesh to binary STL bytes stored in memory.
    Works with numpy-stl 4.12.2 and BytesIO.
    """
    buf = io.BytesIO()

    # 80-byte header
    header = b"Generated by image_to_stl"[:80]
    buf.write(header.ljust(80, b" "))

    # Number of triangles
    buf.write(struct.pack("<I", len(stl_mesh.data)))

    # Each triangle: normal + 3 vertices + attribute byte count
    for tri in stl_mesh.data:
        # Normal vector
        buf.write(struct.pack("<3f", *tri['normals']))

        # Triangle vertices
        for vertex in tri['vectors']:
            buf.write(struct.pack("<3f", *vertex))

        # Attribute byte count (always 0)
        buf.write(struct.pack("<H", 0))
        
    return buf.getvalue()


def main():
    if len(sys.argv) < 4:
        print("Usage: python image_to_stl.py <input_image> <max_height> <blur_radius>")
        return

    input_file = sys.argv[1]
    max_height = float(sys.argv[2])
    blur_radius = int(sys.argv[3])

    # Load image
    img = Image.open(input_file)

    # Fix transparent PNG (flatten over white)
    if img.mode in ("RGBA", "LA"):
        background = Image.new("RGB", img.size, (255, 255, 255))
        background.paste(img, mask=img.split()[-1])
        img = background

    # Convert to grayscale and blur
    img = img.convert("L").filter(ImageFilter.GaussianBlur(radius=blur_radius))

    # Convert image into height map (black = high, white = low)
    data = (1.0 - (np.array(img) / 255.0)) * max_height
    data = np.flipud(data)

    height, width = data.shape
    num_triangles = (width - 1) * (height - 1) * 2

    # Create STL mesh
    stl_mesh = mesh.Mesh(np.zeros(num_triangles, dtype=mesh.Mesh.dtype))

    tri_index = 0
    scale = 0.01  # millimeter units

    for y in range(height - 1):
        for x in range(width - 1):
            h1, h2 = data[y, x], data[y, x+1]
            h3, h4 = data[y+1, x], data[y+1, x+1]

            X0, X1 = x * scale, (x + 1) * scale
            Y0, Y1 = y * scale, (y + 1) * scale

            h1 *= scale
            h2 *= scale
            h3 *= scale
            h4 *= scale

            stl_mesh.vectors[tri_index] = np.array([
                [X0, Y0, h1],
                [X1, Y0, h2],
                [X0, Y1, h3]
            ])
            tri_index += 1

            stl_mesh.vectors[tri_index] = np.array([
                [X1, Y0, h2],
                [X1, Y1, h4],
                [X0, Y1, h3]
            ])
            tri_index += 1

    # Convert to bytes in memory
    stl_bytes = mesh_to_stl_bytes(stl_mesh)

    # Output bytes to stdout (Java will read this!)
    sys.stdout.buffer.write(stl_bytes)


if __name__ == "__main__":
    main()